name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --scope=tmarchum-3232s-projects
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=tmarchum-3232s-projects
        env:
          VERCEL_ORG_ID: team_YZGR71Y1CyqYACLXNfHkPckK
          VERCEL_PROJECT_ID: prj_OwsOAEW5cKfzqA4O1B7VkRm2Y8VJ
